#!/usr/bin/env bash
set -e

this_dir="$(readlink -f "$(dirname "$0")")"

# Make sure your AppImage uses the bundled libraries first
export LD_LIBRARY_PATH="$this_dir"/usr/local/lib:"$LD_LIBRARY_PATH"

# Run your binary
exec "$this_dir"/usr/local/bin/crun "$@"
